### ISSUE TITLE
fix handling of long long 

### ISSUE THREAD

**Issue by springmeyer** [mapnik/Ruby-Mapnik#32]
lots of compiler warnings currently against mapnik v2.2.0 due to poor handling of the new 64bit `long long` type of `mapnik::value_integer`. This needs work, but was over my head at the time given my lack of ruby/rice experience. Hoping @elliotlaster can take a look.

**Comment by timwaters** [comment]
still seeing errors for v.2.2.0-pre

**Comment by springmeyer** [comment]
@timwaters - I'm not actively maintaining Ruby-Mapnik, but I'm happy to accept pull requests or to grant you commit access to make fixes. Let me know if you'd be keen with either. /cc @gravitystorm.

**Comment by timwaters** [comment]
@springmeyer thanks - my C++  / Rice knowledge is almost as non existent as my knowledge of the Mapnik library :smile:  But I can hack away and it might help others if they search for similar issues.
