### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by gravitystorm** [mapnik/Ruby-Mapnik#49]
I thought it best to write down what my thoughts are with the status of this project! Apologies for the stream-of-consciousness post.

* Dane doesn't have time to be maintainer
* Elliot hasn't responded to any attempts at contact
* Nobody else has stepped forward
* I guess that buck stops with me

The main problem is that I have neither the experience with rubygems nor especially with rice to feel confident about what I'm doing!

My plan is as follows:

### Rename the gem to "mapnik" and publish to rubygems
We don't have access to the old ruby_mapnik account on rubygems, and the name is slightly weird for a gem anyway. Moreover, if I manage to break things, any existing projects with `gem ruby_mapnik` will be unaffected

### Find a method to build+test locally
I want to be able to build the gem a) in an isolated environment (so that I can try multiple versions of mapnik without ruining my environment) b) locally (so that I'm not depending on travis). I've started exploring using test-kitchen which I normally use for testing chef-recipes across platforms, since it has a large overlap in features for what I need here.

### Expand supported platforms, ruby, and mapnik versions
I would like to expand support and therefore the testing setup to cover:
* all supported ruby versions (e.g. 1.9.3, 2.1.x, 2.2.x)
* all the main mapnik versions (e.g. 2.2.0, 2.3.x, 3.0.x)
* ubuntu 12.04 and 14.04
* other OSes like fedora

### Accept every PR
Yep. Since my time is very limited and my knowledge too, once I have a way to run the tests I'll accept pretty much any PR that doesn't break the build. And if something bad slips through, then we write more tests.

### Find more maintainers
I'm keeping a very keen eye out for anyone who can help with any aspects of this. My aim is to have at least 2 other people who can release and who also feel comfortable releasing new versions of the gem.

Feedback welcome!

**Comment by springmeyer** [comment]
:+1: to every one of these ideas.

> Dane doesn't have time to be maintainer

That and I don't know how to write ruby or really anything about the language. So, I can be useful where mapnik touches rice, but not much after that.

**Comment by gordonk** [comment]
Andy I'm happy to help.  I've hacked it about getting it to run with ruby 2.1.6 and rice 0.7, but it needs a bit more love to get running with 2.2.

**Comment by gravitystorm** [comment]
OK, new release is at https://rubygems.org/gems/mapnik - finally! Now lets see if it works for anyone else, or just me :-)

@gordonk it would be great to have your help, feel free to create some pull requests for any changes that you've made.

**Comment by gravitystorm** [comment]
I'm going to close this issue for now since we seem to have agreement on the plan - we can open individual issues as we go along.
